Default: &defaults
  database: project1.sqlite3
  poolsize: 10

Development:
  <<: *defaults

Testing:
  database: project1_test.sqlite3
  <<: *defaults

Staging:
  database: project1_staging.sqlite3
  poolsize: 100
  <<: *defaults

Production:
  database: project1_production.sqlite3
  poolsize: 100
  <<: *defaults
